### ISSUE TITLE
arrows with label not recognized

### ISSUE THREAD

**Issue by ojob** [ytisf/language-mermaid#5]
I've got the following code block:

    graph LR
      C --> D
      A -.dse.-> B
      A --dse--> B
      A -.-> D

And here's how it looks with the syntax highlighting:
![image](https://user-images.githubusercontent.com/1648261/71153490-851d6d80-2239-11ea-86c4-dc1d35bcdc5f.png)

i.e. there is not syntax highlighting for the lines with a label within the arrow.

(for the records: the diagram is correcly rendered
![image](https://user-images.githubusercontent.com/1648261/71153543-a5e5c300-2239-11ea-8267-867e8ea94254.png)
)

So it seems that the arrow labelling is not recognized, even thought they seem to be defined in [the grammar](https://github.com/ytisf/language-mermaid/blob/7305c5bfd953112b6266a537d85f9251778983b8/grammars/mermaid.cson#L76).

Any idea what's wrong?

Installation informations :
* atom 1.41.0 x64
* language-mermaid 0.6.0

**Comment by ytisf** [comment]
Thanks Joel . 
Last commit should fix this issue.

**Comment by ojob** [comment]
Hi, thanks for quick feedback! However, as for #6, I replaced the file .atom\packages\language-mermaid\grammars\mermaid.cson with the content as per commit 7c8734e.

But from the same example :

```
graph LR
  C --> D
  A -.dse.-> B
  A --dse--> B
  A -.-> D
  
```
I still get no coloring for the labelled arrows:
![image](https://user-images.githubusercontent.com/1648261/71240760-3db2e200-230a-11ea-83c7-3257bc36afd6.png)

I also tried something different, just to see:

```
graph LR
  A -.dse.-> B
  A --dse--> B
  A -.-> D
  %% with something weird inside :
  C --e-e-e--> D
```

Which looks as follows (watch last line):
![image](https://user-images.githubusercontent.com/1648261/71240731-2aa01200-230a-11ea-897e-a839da254732.png)

Which made me think of a very subtle difference, with no space between box labels and arrows starts/ends:

```
graph LR
  C-->D
  A-.dse.->B
  A--dse-->B
  A-.->D
```
  
![image](https://user-images.githubusercontent.com/1648261/71240874-836faa80-230a-11ea-8cfe-26bb914fdf3a.png)

So, for this last example, we have a somehow nice coloring for arrows with label or dots, but that goes a bit further than the arrow, and no coloring for the basic case if we have no space between Box label `C` and arrow start.
